FROM docker.io/php:8.0-fpm-alpine

COPY --from=docker.io/mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions gd \
    opcache \
    pgsql \
    zip \
    redis \
    pdo_pgsql \
    pdo_mysql \
    sockets \
    bz2 \
    pcntl \
    bcmath \
    rdkafka \
    sqlsrv \
    pdo_sqlsrv \
    exif \
    swoole

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

COPY --from=docker.io/composer:2 /usr/bin/composer /usr/bin/composer

COPY /8.0/opcache.ini $PHP_INI_DIR/conf.d/
COPY /8.0/php.ini $PHP_INI_DIR/conf.d/

FROM ghcr.io/roadrunner-server/roadrunner:latest AS roadrunner
COPY --from=roadrunner /usr/bin/rr /usr/local/bin/rr